### ISSUE TITLE
Test and perform slot handover process

### ISSUE THREAD

**Issue by clangenb** [integritee-network/parachain#166]
According to the guideline in #162.

1. Create local setup with either polkadot-js or zombie net, which launches one integritee-chain and one shell-runtime.
2. [on relay chain] Call registrar.swap(lease1-id, lease2-id) signed by the account that registered the lease-1 paraId.
4. [on relay chain] Call registrar.swap(lease2-id, lease1-id) signed by the account that registered the lease-2 paraId.
5. [on relay chain] Verify that the leas is extended. Todo: How do we do this? Should be a simple as querying a simple storage value.

Open question: can we configure the local setup to have different lease periods for the two parachains, so we can really verify that it worked?

Some useful links from the other issue:
* https://wiki.polkadot.network/docs/learn-auction#parachain-lease-extension
* https://substrate.stackexchange.com/questions/2874/how-can-a-project-prolong-a-parachain-slot-lease-in-kusama/2887#2887
* https://substrate.stackexchange.com/questions/4518/parachain-lease-extension-swap-paraid-as-well
* [Swap extrinsic](https://github.com/paritytech/polkadot/blob/9f656191ab24e0e79e6386c65e413d478a207185/runtime/common/src/paras_registrar.rs#L264).

**Comment by coax1d** [comment]
Ok going down the rabbit hole doing this verification via zombienet or polkadot-launch is not possible given the current state of both tools and polkadot itself. Allow me to explain..

Zombienet particularly and also polkadot-launch register parachains to the relay chain in two ways. The first way they will add the parachains to the genesis this is the `add_to_genesis` flag in the `parachains` section of a zombienet toml. The second way is to call `sudo_schedule_para_initialize()` in the Polkadot Runtime Module `paraSudoWrapper`.

This should feel familiar if you have manually added parachains in the past to a local relay chain.

The issue is that we want to call `registrar.swap()`. The `registrar.swap()` function performs a check which checks to see whether the signer is the relaychain root, the parachain itself, or the individual who reserved the para_id.  When a parachain_id is reserved using the registrar pallet the signers pub_key is saved along with some information pertaining to the parachain lock shown here: [Parachain Info](https://github.com/paritytech/polkadot/blob/4ac7d94069a6faeb3c4145732b6d7a4b74aa798a/runtime/common/src/paras_registrar.rs#L44-L52)

However if one does not reserve the para_id in this fashion they will not beable to call `swap()` in the Registrar Module unless they are root. They will never get past this check in the `swap()` function [Here](https://github.com/paritytech/polkadot/blob/4ac7d94069a6faeb3c4145732b6d7a4b74aa798a/runtime/common/src/paras_registrar.rs#L282-L283)

What this means is that Zombienet unless utilizing some very high level JS trickery and hacking is not suitable to complete this task not just from a verification standpoint but even how it chooses to register parachains. It is possible for Polkadot to support this by allowing `sudo_schedule_para_initialize()` to not only reserve a slot and onboard a parachain but to also take a pub key which can be stored as the manager of this slot. Right now it is very misleading because if you actually check the chainstate of the `registrar` module when using `sudo_schedule_para_initialize()` to register a new parachain you will actually see that even though the para_id is reserved there is no way to see any information on who reserved it via the `Paras` Storage item [Shown Here](https://github.com/paritytech/polkadot/blob/4ac7d94069a6faeb3c4145732b6d7a4b74aa798a/runtime/common/src/paras_registrar.rs#L180-L186)

All in all this means that the best way for verification of this `swap()` feature is to spin it up a local rococo relay chain manually, build each genesis state and wasm blob separately for the integritee-shell-runtime and integritee-runtime respectively, register them at different time points so that their lease periods overlap but are not equal and to reserve the paraids of both parachains using a known signer like `Alice`. After all this one should call `swap(para_id1, para_id2) && swap(para_id2, para_id1)` and see if the lease times update.

**Comment by coax1d** [comment]
Confirmed that slot hand over process works. In order to reproduce this locally do the following:
- Start local relay chain validators with `rococo-local` chain spec
- Start local integritee-parachain collator for `integritee-shell-runtime` using `shell-rococo-local-dev` chain spec with 
paraId `2015` (Or one of your choosing) start with `--dave` flag for Aura Keys to be correct
- Start local integritee-parachain collator for `integritee-runtime` using `integritee-rococo-local-dev` chain spec with paraId 
`2016` (Or a different one of your choosing make sure it is different from `shell-runtime` paraId` start with `--dave` flag for Aura Keys to be correct
- Register ParaId for `shell-runtime` and `integritee-runtime` respectively
- extrinsics -> registrar -> register() to reserve onboard as parathread for both runtimes
- sudo -> slots -> forceLease() for `shell-runtime` choose 0 - 100 do again for `integritee-runtime` choose 0 - 200
- both parachains are onboarded and producing blocks
- sudo -> forceRemoveLock for both paraIds (This will allow you to call swap from extrinsics instead of sudo)
- extrinsics -> registrar -> swap(para_id1, para_id2)
- extrinsics -> registrar -> swap(para_id2, para_id1)
- view in Polkadot JS that the leases have swapped periods with one another. Now `shell-runtime` will have 0-200 periods and `integritee-runtime` will have 0-100 periods

Requesting this be closed now by @clangenb

**Comment by clangenb** [comment]
Thanks @coax1d for this elaborate documentation. I can trust now that the procedure we have in mind works! 👍

I made a new issue for the slot lease swap on the Kusama parachain, please review: #169
