### ISSUE TITLE
Kusama 2nd slot swap

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#212]
check how we did last time: https://github.com/integritee-network/parachain/issues/181

fresh paraid 2267 which has a lease for LP30 - 37
old paraid 2015 which has 30-31 left
current lease: 30

this should be the release registered for the parathread
https://github.com/integritee-network/parachain/releases/tag/1.5.35

**Comment by clangenb** [comment]
Shell-runtime has successfully requested the slot swap on kusama, but we need an integritee-runtime upgrade before we can do the slot swap there because of #225. However, we know that we can safely upgrade without breaking UMP because we tested it with the shell-runtime.

**Comment by clangenb** [comment]
Path forward:
- [ ] Merge #227 
- [ ] Release new runtime
- [ ] #219 
- [ ] Propose slot swap analogous to picture below (note: para ids need to be switched compared to the ones in the image):
![image](https://github.com/integritee-network/parachain/assets/37865735/7ad094f6-2f8a-4ffd-9f13-cb2ea2602c5a)

**Comment by brenzi** [comment]
XCM failed:

https://integritee.subscan.io/event?address=&module=scheduler&event=all&startDate=&endDate=&startBlock=&endBlock=&timeType=date&version=29

**Comment by clangenb** [comment]
The issue is identified. The default XCM version was set to 2, and there was no overwrite for the relay chain, this lead to a destination unsupported error, as the relay chains seems to accept XCM version 3 only now. Our freshly started shell parachain did indeed have that version overwrite set for the relay chain, as its first block was produced after the relay chain migrated to version 3, and then it was notified by the relay chain about its current XCM version.

I could successfully send the slot swap UMP to the relay chain on Rococo after manually setting the XCM version to 3 for the relay chain destination.

In general, I am wondering:
* If we can migrate our default XCM version to 3 (I think so): https://github.com/integritee-network/parachain/issues/232
* If we should subscribe to XCM version updates (I think so): https://github.com/integritee-network/parachain/issues/231

**Comment by clangenb** [comment]
Slot swap was successful 🥳 

* See successful extrinsic on Integritee: https://integritee.subscan.io/extrinsic/0x7203249c0f111eae508d00e2ab940cbac09a296349384386bb0366b7d0c0fa25

* See slot swap event on kusama: https://kusama.subscan.io/block/18976366?tab=event

* See updated lease period on subscan: https://kusama.subscan.io/parachain/2015
