### ISSUE TITLE
cross-parachain token transfer in local setup

### ISSUE THREAD

**Issue by brenzi** [integritee-network/parachain#98]
resources:
* a primer on cross-chain messaging: https://www.youtube.com/watch?v=5cgq5jOZx9g
* basic local setup with hrmp: https://docs.substrate.io/tutorials/v3/cumulus/polkadot-launch/
* theory: https://wiki.polkadot.network/docs/learn-crosschain

setup polkadot-launch with rococo-local
* Integritee parachain
* [Karura Parachain](https://github.com/AcalaNetwork/Acala/tree/master/runtime/karura)

See [Acala's Integration guide](https://wiki.acala.network/build/development-guide/composable-chains#integration-guide)
* skip step 2, we don't want to include their tokesn on our chain. only TEER token on theirs

Transfer TEER tokens from integritee parachain to Karura parachain (where TEER is an asset which needs to be registered)

**Comment by haerdib** [comment]
Sending Token to Acala with xToken pallet:

![grafik](https://user-images.githubusercontent.com/73821294/164736041-95f325ef-ec1b-4779-b416-16f060ee9ce4.png)

destWeight must be atleast twice the fees, otherwise the Acala barrier will block.

Sending Token from Acala back to Integritee (rococo local parachain Id 2001)
![grafik](https://user-images.githubusercontent.com/73821294/164736154-1116bbd4-28ae-4b8a-97e0-9d225f259f3d.png)

More documentation will follow.
